name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'yarn.lock'
      - '.github/workflows/main.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'yarn.lock'
      - '.github/workflows/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1

      ## Test
      - name: Run unit tests
        run: yarn test:ci

      - name: Run Cypress tests
        run: |
          yarn start
          yarn test:ci-e2e
          sleep 2
          yarn test:ci-components

      - name: Upload artifacts on fail
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: videos
          path: tests/e2e/videos/
